---
# vars file for TP_INI

Nombre_Grupo: "Andres_Frias"
Division: "313"

R1:
  Nombre: Andres
  Apellido: Frias

R2:
  Nombre: Andres
  Apellido: Frias

R3:
  Nombre: Andres
  Apellido: Frias

R4:
  Nombre: Andres
  Apellido: Frias

R5:
  Nombre: Andres
  Apellido: Frias

R6:
  Nombre: Andres
  Apellido: Frias

