version: '3'

services:
    web:
        #image: andresfrias91/tp_div_313_andres_frias
        image: tp_div_313_andres_frias
        ports:
            - "8081:80"
        volumes:
          #- $PWD/web/file:/usr/share/nginx/html/file andresfrias91/tp_div_313_andres_frias
          $PWD/web/file:/usr/share/nginx/html/file tp_div_313_andres_frias

