# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # ── VM1 : Ubuntu (Testing) ──────────────────────────────
  config.vm.define "VM1-Grupo-AndresFrias" do |vmHost1|
    vmHost1.vm.box = "ubuntu/jammy64"
    vmHost1.vm.hostname = "VM1-Grupo-AndresFrias"
    vmHost1.vm.network "private_network", :name => '', ip: "192.168.56.10"
    
    # Comparto la carpeta del host donde estoy parado contra la vm
    vmHost1.vm.synced_folder 'compartido_Host1/', '/home/vagrant/compartido', 
    owner: 'vagrant', group: 'vagrant' 

      # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
      vmHost1.ssh.insert_key = true
      # Agrego los disco 
	  vmHost1.vm.disk :disk, size: "5GB", name: "#{vmHost1.vm.hostname}_extra_storage_5GB"
	  vmHost1.vm.disk :disk, size: "3GB", name: "#{vmHost1.vm.hostname}_extra_storage_3GB"
	  vmHost1.vm.disk :disk, size: "2GB", name: "#{vmHost1.vm.hostname}_extra_storage_2GB"
	  vmHost1.vm.disk :disk, size: "1GB", name: "#{vmHost1.vm.hostname}_extra_storage_1GB"

      vmHost1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "VM1-Grupo-AndresFrias"
        vb.cpus = 1
        vb.linked_clone = true
        vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']      
      end    
      # Puedo Ejecutar un script que esta en un archivo
      vmHost1.vm.provision "shell", path: "script_Enable_ssh_password.sh"
      vmHost1.vm.provision "shell", privileged: false, path: "script_Fix_history.sh"
      vmHost1.vm.provision "shell", path: "instala_paquetes.sh"
      vmHost1.vm.provision "shell", privileged: false, inline: <<-SHELL
      # Los comandos aca se ejecutan como vagrant
  
      mkdir -p /home/vagrant/repogit
      cd /home/vagrant/repogit
      git clone https://github.com/upszot/UTN-FRA_SO_onBording.git 
      git clone https://github.com/upszot/UTN-FRA_SO_Ansible.git
      git clone https://github.com/upszot/UTN-FRA_SO_Docker.git
	  git clone https://github.com/Andrestone91/TP_AySO_Integral_AndresFrias.git
	  git clone https://github.com/upszot/UTN-FRA_SO_TP-Integral.git
	  
	  echo "192.168.56.10 VM1-Grupo-AndresFrias" | sudo tee -a /etc/hosts
      echo "192.168.56.11 VM2-Grupo-AndresFrias" | sudo tee -a /etc/hosts
      echo "vagrant ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/vagrant
    SHELL
    end
    
     # ── VM2 : Fedora (Producción) ───────────────────────────
    config.vm.define "VM2-Grupo-AndresFrias" do |vmHost2|
      vmHost2.vm.box = "generic/fedora33"
      vmHost2.vm.hostname = "VM2-Grupo-AndresFrias"
      vmHost2.vm.network "private_network", :name => '', ip: "192.168.56.11"
      
      # Comparto la carpeta del host donde estoy parado contra la vm
      vmHost2.vm.synced_folder 'compartido_Host2/', '/home/vagrant/compartido'
  
    # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
    vmHost2.ssh.insert_key = true
	
	# Agrego los disco 
	vmHost2.vm.disk :disk, size: "5GB", name: "disk_5G_vm2"
    vmHost2.vm.disk :disk, size: "3GB", name: "disk_3G_vm2"
    vmHost2.vm.disk :disk, size: "2GB", name: "disk_2G_vm2"
    vmHost2.vm.disk :disk, size: "1GB", name: "disk_1G_vm2"
	
    vmHost2.vm.provider "virtualbox" do |vb2|
      vb2.memory = "1024"
      vb2.name = "VM2-Grupo-AndresFrias"
      vb2.cpus = 1
      vb2.linked_clone = true
      # Seteo controladora Grafica
      vb2.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end
    
    # Puedo Ejecutar un script que esta en un archivo
    vmHost2.vm.provision "shell", path: "script_Enable_ssh_password.sh"
    vmHost2.vm.provision "shell", privileged: false, path: "script_Fix_history.sh"
	
    # Provisión para instalar
    vmHost2.vm.provision "shell", inline: <<-SHELL
	
	  mkdir -p /home/vagrant/repogit
      cd /home/vagrant/repogit
      git clone https://github.com/upszot/UTN-FRA_SO_onBording.git 
      git clone https://github.com/upszot/UTN-FRA_SO_Ansible.git
      git clone https://github.com/upszot/UTN-FRA_SO_Docker.git
	  git clone https://github.com/Andrestone91/TP_AySO_Integral_AndresFrias.git
	  git clone https://github.com/upszot/UTN-FRA_SO_TP-Integral.git
	  
      dnf install -y /home/vagrant/compartido/tree-1.8.0-10.el9.x86_64.rpm
	  
	  echo "192.168.56.10 VM1-Grupo-AndresFrias" | sudo tee -a /etc/hosts
      echo "192.168.56.11 VM2-Grupo-AndresFrias" | sudo tee -a /etc/hosts
      echo "vagrant ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/vagrant
    SHELL
  end
end
